const FILE_LIST = [ 
  "images/Burger/Burger 1/bleu-removebg-preview.png",
  "images/Burger/Burger 1/doré-removebg-preview.png",
  "images/Burger/Burger 1/gold-removebg-preview.png",
  "images/Burger/Burger 1/gris-removebg-preview.png",
  "images/Burger/Burger 1/noir-removebg-preview.png",
  "images/Burger/Burger 1/rouge-removebg-preview.png",
  "images/Burger/Burger 1/vert-removebg-preview.png",
  "images/Burger/Burger 1/violet-removebg-preview.png",
  "images/Burger/Burger 2/blanc-removebg-preview (1).png",
  "images/Burger/Burger 2/blanc-removebg-preview.png",
  "images/Burger/Burger 2/Blanc_vide-removebg-preview.png",
  "images/Burger/Burger 2/bleu-removebg-preview.png",
  "images/Burger/Burger 2/Bleu_Vert-removebg-preview.png",
  "images/Burger/Burger 2/doré-removebg-preview.png",
  "images/Burger/Burger 2/doré_vide-removebg-preview.png",
  "images/Burger/Burger 2/Doréé-removebg-preview.png",
  "images/Burger/Burger 2/rose-removebg-preview.png",
  "images/Burger/Burger 2/rouge-removebg-preview.png",
  "images/Burger/Burger 2/Vert-removebg-preview.png",
  "images/Burger/Burger 2/Violet-removebg-preview.png",
  "images/Cercle Vide/2-removebg-preview.png",
  "images/Cercle Vide/2_cercles-removebg-preview (1).png",
  "images/Cercle Vide/Capture-removebg-preview.png",
  "images/Cercle Vide/cecle-removebg-preview.png",
  "images/Cercle Vide/fleur-removebg-preview.png",
  "images/Cercle Vide/point-removebg-preview.png",
  "images/Cercle Vide/tait-removebg-preview.png",
  "images/Kebab/Kebab 1/Blanc-removebg-preview.png",
  "images/Kebab/Kebab 1/bleu-removebg-preview.png",
  "images/Kebab/Kebab 1/Doré-removebg-preview.png",
  "images/Kebab/Kebab 1/Gris-removebg-preview.png",
  "images/Kebab/Kebab 1/jaune-removebg-preview.png",
  "images/Kebab/Kebab 1/Noir-removebg-preview.png",
  "images/Kebab/Kebab 1/Rose-removebg-preview.png",
  "images/Kebab/Kebab 1/rouge-removebg-preview.png",
  "images/Kebab/Kebab 1/Vert-removebg-preview.png",
  "images/Kebab/Kebab 2/Blanc-removebg-preview.png",
  "images/Kebab/Kebab 2/Bleu-removebg-preview.png",
  "images/Kebab/Kebab 2/Degradé-removebg-preview.png",
  "images/Kebab/Kebab 2/golden-removebg-preview.png",
  "images/Kebab/Kebab 2/gris-removebg-preview.png",
  "images/Kebab/Kebab 2/Jaune-removebg-preview.png",
  "images/Kebab/Kebab 2/Jaune_plein-removebg-preview.png",
  "images/Kebab/Kebab 2/Rose-removebg-preview.png",
  "images/Kebab/Kebab 2/Rouge-removebg-preview.png",
  "images/Kebab/Kebab 2/Vert-removebg-preview.png",
  "images/Kebab/Kebab 3/BLEU-removebg-preview.png",
  "images/Kebab/Kebab 3/DEGRAD2-removebg-preview.png",
  "images/Kebab/Kebab 3/DEGRAD3-removebg-preview.png",
  "images/Kebab/Kebab 3/Gold-removebg-preview.png",
  "images/Kebab/Kebab 3/gris-removebg-preview.png",
  "images/Kebab/Kebab 3/JAUNEE-removebg-preview.png",
  "images/Kebab/Kebab 3/ROUGE-removebg-preview.png",
  "images/Kebab/Kebab 3/VERT-removebg-preview.png",
  "images/Kebab/Kebab 3/VIOLET-removebg-preview.png",
  "images/Neutre/Neutre 1/Blanc-removebg-preview.png",
  "images/Neutre/Neutre 1/Degradé-removebg-preview.png",
  "images/Neutre/Neutre 1/Doré-removebg-preview.png",
  "images/Neutre/Neutre 1/Gold-removebg-preview.png",
  "images/Neutre/Neutre 1/Gris-removebg-preview.png",
  "images/Neutre/Neutre 1/Jaune-removebg-preview.png",
  "images/Neutre/Neutre 1/Rouge-removebg-preview.png",
  "images/Neutre/Neutre 1/turquoise-removebg-preview.png",
  "images/Neutre/Neutre 1/Vert-removebg-preview.png",
  "images/Neutre/Neutre 1/Vert_2-removebg-preview.png",
  "images/Neutre/Neutre 1/Violet-removebg-preview.png",
  "images/Pizza/Pizza 1/Bleu.png",
  "images/Pizza/Pizza 1/Degardé 1.png",
  "images/Pizza/Pizza 1/Degradé 2.png",
  "images/Pizza/Pizza 1/Dégradé 3.png",
  "images/Pizza/Pizza 1/Dégradé 4.png",
  "images/Pizza/Pizza 1/Orange.png",
  "images/Pizza/Pizza 1/Palier Vide 0.png",
  "images/Pizza/Pizza 1/Palier Vide 1.png",
  "images/Pizza/Pizza 1/Rouge.png",
  "images/Pizza/Pizza 1/Vert.png",
  "images/Pizza/Pizza 1/Vide 0.png",
  "images/Pizza/Pizza 1/Vide 1.png",
  "images/Pizza/Pizza 1/Vide 2.png",
  "images/Pizza/Pizza 1/Vide.png",
  "images/Pizza/Pizza 2/Gemini_Generated_Image_6zyr4s6zyr4s6zyr-removebg-preview.png",
  "images/Pizza/Pizza 2/Gemini_Generated_Image_7fvko77fvko77fvk-removebg-preview.png",
  "images/Pizza/Pizza 2/Gemini_Generated_Image_bji19cbji19cbji1-removebg-preview.png",
  "images/Pizza/Pizza 2/Gemini_Generated_Image_csm55ocsm55ocsm5-removebg-preview.png",
  "images/Pizza/Pizza 2/Gemini_Generated_Image_trnsb8trnsb8trns-removebg-preview.png",
  "images/Pizza/Pizza OrArgent/Gemini_Generated_Image_97pbmg97pbmg97pb-removebg-preview.png",
  "images/Pizza/Pizza OrArgent/Gemini_Generated_Image_akkvetakkvetakkv-removebg-preview.png",
  "images/Pizza/Pizza OrArgent/Gemini_Generated_Image_b53u50b53u50b53u-removebg-preview.png",
  "images/Pizza/Pizza OrArgent/Gemini_Generated_Image_cc7xxccc7xxccc7x-removebg-preview.png",
  "images/Pizza/Pizza OrArgent/Gemini_Generated_Image_vj9rqevj9rqevj9r-removebg-preview.png",
  "images/Pizza/Pizza OrArgent/Gemini_Generated_Image_yd065myd065myd06-removebg-preview.png",
  "images/Poulet/Nouveau projet (10).png",
  "images/Poulet/Nouveau projet (11).png",
  "images/Poulet/Nouveau projet (12).png",
  "images/Poulet/Nouveau projet (13).png",
  "images/Poulet/Nouveau projet (9).png",
  "images2/Circulaire/bleu-removebg-preview.png",
  "images2/Circulaire/Doré-removebg-preview.png",
  "images2/Circulaire/gris-removebg-preview.png",
  "images2/Circulaire/jaune_clair-removebg-preview.png",
  "images2/Circulaire/Rose-removebg-preview.png",
  "images2/Circulaire/Rouge-removebg-preview.png",
  "images2/Circulaire/vert-removebg-preview.png",
  "images2/Circulaire/Violet-removebg-preview.png",
  "images2/Donut/Donut 1/plein recompense.png",
  "images2/Donut/Donut 1/plein.png",
  "images2/Donut/Donut 1/Vide recompense.png",
  "images2/Donut/Donut 1/Vide.png",
  "images2/Fleurs/Fleur 1/Blanc 2.png",
  "images2/Fleurs/Fleur 1/Blanc.png",
  "images2/Fleurs/Fleur 1/Bleu vert.png",
  "images2/Fleurs/Fleur 1/Bleu.png",
  "images2/Fleurs/Fleur 1/Gold.png",
  "images2/Fleurs/Fleur 1/Rose.png",
  "images2/Fleurs/Fleur 1/Rouge.png",
  "images2/Fleurs/Fleur 1/Shiny.png",
  "images2/Indien/Indien 1/Doré-removebg-preview.png",
  "images2/Indien/Indien 1/Noir-removebg-preview.png",
  "images2/Indien/Indien 1/Orange-removebg-preview.png",
  "images2/Indien/Indien 1/Rouge-removebg-preview.png",
  "images2/Indien/Indien 1/Vert-removebg-preview.png",
  "images2/Indien/Indien 2/Doré-removebg-preview.png",
  "images2/Indien/Indien 2/Gris-removebg-preview.png",
  "images2/Indien/Indien 2/Orange-removebg-preview.png",
  "images2/Indien/Indien 2/Vert-removebg-preview.png",
  "images2/Indien/Indien 2/Vert_Orange-removebg-preview.png",
]; 
